Repository boostcampwm-2024/web38-Froxy, pull requests merged in 2024-12, with the labels that each got.

#190 fix: 병합 과정에서 잘못 반영된 FE 수정하기
  apps/frontend/src/feature/codeView/index.tsx
  apps/frontend/src/feature/comment/index.tsx
  apps/frontend/src/shared/.gitkeep
  apps/frontend/src/widget/.gitkeep
  apps/frontend/src/widget/lotusList/index.tsx
Labels: 🐞 BugFix, 💻 Fe

#193 Fix(#192): LotusGistLink를 Button으로 변경
  apps/frontend/src/feature/lotus/component.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
Labels: 💻 Fe, ♻️ Refactor

#188 Fix #184 fix db entities
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/comment/comment.entity.ts
  apps/backend/src/config/queue.config.ts
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/constants/constants.ts
  apps/backend/src/docker/docker.consumer.ts
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.module.ts
  apps/backend/src/docker/docker.pool.ts
  apps/backend/src/docker/docker.producer.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/history/dto/history.responseList.dto.ts
  apps/backend/src/history/history.controller.ts
  apps/backend/src/history/history.entity.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/lotus/dto/lotus.detail.dto.ts
  apps/backend/src/lotus/dto/lotus.dto.ts
  apps/backend/src/lotus/dto/lotus.response.dto.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.entity.ts
  apps/backend/src/lotus/lotus.module.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/relation/lotus.tag.entity.ts
  apps/backend/src/relation/lotus.tag.module.ts
  apps/backend/src/relation/lotus.tag.repository.ts
  apps/backend/src/relation/lotus.tag.service.ts
  apps/backend/src/tag/tag.controller.ts
  apps/backend/src/tag/tag.entity.ts
  apps/backend/src/tag/tag.service.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.entity.ts
  apps/backend/src/user/user.service.ts
  pnpm-lock.yaml
Labels: 🐞 BugFix, 💻 Be

#195 Feature #194 도메인 모델 객체 테스트 추가
  apps/frontend/src/feature/codeView/model/index.ts
  apps/frontend/src/feature/codeView/model/model.test.ts
  apps/frontend/src/feature/codeView/model/model.ts
  apps/frontend/src/feature/history/model/index.ts
  apps/frontend/src/feature/history/model/model.test.ts
  apps/frontend/src/feature/history/model/model.ts
  apps/frontend/src/feature/lotus/model/index.ts
  apps/frontend/src/feature/lotus/model/model.test.ts
  apps/frontend/src/feature/lotus/model/model.ts
  apps/frontend/src/feature/pagination/index.ts
  apps/frontend/src/feature/pagination/model.ts
  apps/frontend/src/feature/user/model/index.ts
  apps/frontend/src/feature/user/model/model.test.ts
  apps/frontend/src/feature/user/model/model.ts
Labels: ✅ Test, 💻 Fe

#199 Docs: README 수정하기
  README.md
Labels: 📄 Docs

#200 Refactor #198: 사용자 정보 페이지 리팩토링
  apps/frontend/src/widget/lotusList/SuspenseLotusList.tsx
  apps/frontend/src/widget/lotusList/index.ts
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
Labels: 💻 Fe, ♻️ Refactor

#202 Fix(#201): LotusList 크기가 이상해지는 오류
  apps/frontend/src/widget/lotusList/SuspenseLotusList.tsx
Labels: 🐞 BugFix, 💻 Fe

#206 컨테이너 스케줄링
  .github/workflows/be-cd.yml
  .github/workflows/fe-cd.yml
  apps/backend/src/config/queue.config.ts
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/constants/constants.ts
  apps/backend/src/docker/docker.consumer.ts
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.module.ts
  apps/backend/src/docker/docker.pool.ts
  apps/backend/src/docker/docker.producer.ts
  apps/backend/src/history/history.service.ts
  apps/frontend/src/feature/codeView/type.ts
  apps/frontend/src/feature/user/type.ts
  apps/frontend/src/widget/navigation/index.tsx
  mermaild.md
  npx
Labels: 💻 Be

#203 Feature #191: playwright 적용해서 e2e 테스트하기
  apps/frontend/.gitignore
  apps/frontend/package.json
  apps/frontend/playwright.config.ts
  apps/frontend/src/app/mock/MockRepository/MockRepository.ts
  apps/frontend/src/app/mock/gistResolvers.ts
  apps/frontend/src/app/mock/handlers.ts
  apps/frontend/src/app/mock/historyResolvers.ts
  apps/frontend/src/app/mock/lotusResolvers.ts
  apps/frontend/src/app/mock/userResolvers.ts
  apps/frontend/src/app/test/e2e/lotusDetail.spec.ts
  apps/frontend/src/app/test/e2e/lotusList.spec.ts
  apps/frontend/src/app/test/e2e/user.spec.ts
  apps/frontend/src/feature/history/component.tsx
  apps/frontend/src/feature/lotus/component.tsx
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/lotusDelete/index.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Fe, ♻️ Refactor

#209 fix(#208): api 응답으로 온 시간과 파싱한 시간이 안 맞는 버그 수정
  apps/frontend/src/shared/common/component/Time.tsx
Labels: 🐞 BugFix, 💻 Fe

#205 Refactor #204: mock repository와 controller로 분리하기
  apps/frontend/src/app/mock/MockRepository/MockRepository.ts
  apps/frontend/src/app/mock/controller/gistController.ts
  apps/frontend/src/app/mock/controller/historyController.ts
  apps/frontend/src/app/mock/controller/lotusController.ts
  apps/frontend/src/app/mock/controller/userController.ts
  apps/frontend/src/app/mock/handlers.ts
  apps/frontend/src/app/mock/historyResolvers.ts
  apps/frontend/src/app/mock/lotusResolvers.ts
  apps/frontend/src/app/mock/repository/historyRepository.ts
  apps/frontend/src/app/mock/repository/lotusRepository/index.ts
  apps/frontend/src/app/mock/repository/lotusRepository/lotusMockData.ts
  apps/frontend/src/app/mock/repository/lotusRepository/lotusRepository.ts
  apps/frontend/src/app/mock/repository/userRepository.ts
Labels: 💻 Fe, ♻️ Refactor

#207 Feature #136 api service unit test
  apps/backend/package.json
  apps/backend/src/lotus/lotus.service.spec.ts
  apps/backend/src/lotus/mockLotusData.ts
  apps/backend/src/user/user.service.spec.ts
  apps/backend/src/user/user.service.ts
Labels: ✅ Test, 💻 Be
