Repository boostcampwm-2024/web38-Froxy, pull requests merged in 2024-11, with the labels that each got.

#14 chore(#9): husky 브랜치 이슈번호 자동으로 commit에 라벨링
  .husky/commit-msg
  .husky/pre-commit
Labels: ⚙️ Setting

#19 Feature #18 : 모든 패키지 husky lint-staged 설정, frontendcss tailwindcss 설정 변경
  apps/backend/package.json
  apps/frontend/package.json
  apps/frontend/src/page/about.lazy.tsx
  apps/frontend/tailwind.config.js
  packages/design/package.json
Labels: 🐞 BugFix

#20 Feature #15 : LotusCard 컴포넌트 구현하기
  .vscode/settings.json
  apps/frontend/public/image/exampleImage.jpeg
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/Lotus/Lotus.tsx
  apps/frontend/src/feature/Lotus/index.tsx
  apps/frontend/src/feature/Lotus/type.ts
  apps/frontend/src/page/__root.tsx
  apps/frontend/src/page/lotus.lazy.tsx
  apps/frontend/src/shared/util/formatDateToYYYYMMDD.ts
  apps/frontend/src/widget/LotusList/LotusCardList.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Fe

#26 Feature #25 history UI
  apps/frontend/src/feature/History/index.tsx
  apps/frontend/src/shared/components/Time.tsx
  apps/frontend/src/widget/HistoryList.tsx
  apps/frontend/tsconfig.app.json
  packages/design/package.json
  packages/design/src/App.tsx
  packages/design/src/components/Slot/index.ts
  packages/design/src/components/Slot/types.ts
  packages/design/src/components/index.tsx
  packages/design/src/index.ts
  packages/design/src/main.tsx
Labels: ✨ Feature, 💻 Fe

#24 Feature #22: typography 적용하기
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/typography.tsx
Labels: ✨ Feature, 💻 Fe

#28 Feature #15 : LotusCard 컴포넌트 구현하기
  apps/frontend/package.json
  apps/frontend/public/image/exampleImage.jpeg
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/Lotus/Lotus.tsx
  apps/frontend/src/feature/Lotus/index.tsx
  apps/frontend/src/feature/Lotus/type.ts
  apps/frontend/src/page/__root.tsx
  apps/frontend/src/page/lotus.lazy.tsx
  apps/frontend/src/widget/LotusList/LotusCardList.tsx
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/badge.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Fe

#33 Refactor(#32): typography design 추가로 인한 기존 History, CodeView feature refactor
  apps/frontend/src/feature/History/index.tsx
  apps/frontend/src/widget/HistoryList.tsx
Labels: 💻 Fe, ♻️ Refactor

#30 Feature #29 comment UI
  apps/frontend/src/app/style/github.css
  apps/frontend/src/feature/Comment/Comment.tsx
  apps/frontend/src/feature/Comment/CommentCard.tsx
  apps/frontend/src/feature/Comment/CommentForm.tsx
  apps/frontend/src/feature/Comment/index.tsx
  packages/design/package.json
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/tabs.tsx
Labels: ✨ Feature, 💻 Fe

#27 Feature #5 gist파일 container로 실행하기
  apps/backend/.gitignore
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.module.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/tsconfig.json
Labels: ✨ Feature, 💻 Be

#31 Feature #21 : lotus 검색창 구현하기
  apps/frontend/package.json
  apps/frontend/src/feature/LotusSearch/useLotusSearch.tsx
  apps/frontend/src/page/lotus.lazy.tsx
  apps/frontend/src/widget/LotusList/LotusCardList.tsx
  apps/frontend/src/widget/LotusList/LotusSearchBar.tsx
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/input.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Fe

#39 Feature #36 : 레이아웃 적용 및 헤더 컴포넌트 구현하기
  apps/frontend/public/image/logoIcon.svg
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/page/__root.tsx
  apps/frontend/src/page/index.tsx
  apps/frontend/src/page/lotus.lazy.tsx
  apps/frontend/src/page/lotus/detail/index.tsx
  apps/frontend/src/page/lotus/index.tsx
  apps/frontend/src/page/lotus/route.tsx
  apps/frontend/src/widget/Header.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Fe

#41 git action 으로 cicd 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/test/app.e2e-spec.ts
  packages/react-markdown/vite.config.ts.timestamp-1731397235209-ff03ed3f3f3a4.mjs
  packages/react-markdown/vite.config.ts.timestamp-1731397318219-e73731b71ce51.mjs
  pnpm-lock.yaml
Labels: 💻 Be

#43 Feature #40: pagination 컴포넌트 구현하기
  apps/frontend/package.json
  apps/frontend/src/feature/Pagination/usePagination.tsx
  apps/frontend/src/widget/LotusList/LotusCardList.tsx
  apps/frontend/src/widget/Pagination.tsx
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/pagination.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Fe

#47 typeorm 세팅
  .github/workflows/ci.yml
  apps/backend/package-lock.json
  apps/backend/package.json
  apps/backend/src/ history/history.controller.ts
  apps/backend/src/ history/history.entity.ts
  apps/backend/src/ history/history.module.ts
  apps/backend/src/ history/history.repository.ts
  apps/backend/src/ history/history.service.ts
  apps/backend/src/app.module.ts
  apps/backend/src/comment/comment.controller.ts
  apps/backend/src/comment/comment.entity.ts
  apps/backend/src/comment/comment.module.ts
  apps/backend/src/comment/comment.repository.ts
  apps/backend/src/comment/comment.service.ts
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.entity.ts
  apps/backend/src/lotus/lotus.module.ts
  apps/backend/src/lotus/lotus.repository.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/tag/tag.controller.ts
  apps/backend/src/tag/tag.entity.ts
  apps/backend/src/tag/tag.module.ts
  apps/backend/src/tag/tag.repository.ts
  apps/backend/src/tag/tag.service.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.entity.ts
  apps/backend/src/user/user.module.ts
  apps/backend/src/user/user.repository.ts
  apps/backend/src/user/user.service.ts
  pnpm-lock.yaml
Labels: 💻 Be

#49 Feature #48 : History, CodeViewer 리팩터링
  apps/frontend/src/app/style/github.css
  apps/frontend/src/feature/CodeView/CodeSideBar.tsx
  apps/frontend/src/feature/CodeView/CodeViewProvider.tsx
  apps/frontend/src/feature/CodeView/CodeViewer.tsx
  apps/frontend/src/feature/CodeView/index.tsx
  apps/frontend/src/feature/History/index.tsx
  apps/frontend/src/widget/HistoryList.tsx
Labels: 💻 Fe, ♻️ Refactor

#50 Feature #4 gist api module PR 재등록
  apps/backend/src/app.module.ts
  apps/backend/src/gist/dto/comment.dto.ts
  apps/backend/src/gist/dto/commit.dto.ts
  apps/backend/src/gist/dto/gistApiFile.dto.ts
  apps/backend/src/gist/dto/gistApiFileList.dto.ts
  apps/backend/src/gist/dto/user.dto.ts
  apps/backend/src/gist/gist.controller.spec.ts
  apps/backend/src/gist/gist.controller.ts
  apps/backend/src/gist/gist.module.ts
  apps/backend/src/gist/gist.service.spec.ts
  apps/backend/src/gist/gist.service.ts
Labels: ✨ Feature, 💻 Be

#46 Feature #44 : 사용자 정보 페이지에서 사용자 정보 박스 컴포넌트 구현하기
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/User/UserInfoInputForm.tsx
  apps/frontend/src/page/lotus/user/index.tsx
  apps/frontend/src/widget/LotusList/LotusCardList.tsx
  apps/frontend/src/widget/LotusList/LotusSearchBar.tsx
  apps/frontend/src/widget/User/UserInfoBox.tsx
  packages/design/src/components/ui/typography.tsx
Labels: ✨ Feature, 💻 Fe

#55 Docs readme 수정하기
  README.md
Labels: 📄 Docs

#56 Feature #51: 페이지 경로 정리하고 레이아웃 만들기
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/Comment/Comment.tsx
  apps/frontend/src/feature/Comment/CommentCard.tsx
  apps/frontend/src/feature/History/index.tsx
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/create/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/page/(main)/route.lazy.tsx
  apps/frontend/src/page/(main)/user/index.lazy.tsx
  apps/frontend/src/page/about.lazy.tsx
  apps/frontend/src/page/index.lazy.tsx
  apps/frontend/src/page/index.tsx
  apps/frontend/src/page/lotus/detail/index.tsx
  apps/frontend/src/page/lotus/user/index.tsx
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/HistoryList.tsx
Labels: ✨ Feature, 💻 Fe

#58 Feature #57 ErrorBoundary, AsyncBoundary, useOverlay
  apps/frontend/src/shared/components/AsyncBoundary/AsyncBoundary.tsx
  apps/frontend/src/shared/components/AsyncBoundary/index.ts
  apps/frontend/src/shared/components/ErrorBoundary/ErrorBoundary.test.tsx
  apps/frontend/src/shared/components/ErrorBoundary/ErrorBoundary.tsx
  apps/frontend/src/shared/components/ErrorBoundary/index.ts
  apps/frontend/src/shared/hooks/useOverlay/OverlayProvider.tsx
  apps/frontend/src/shared/hooks/useOverlay/index.tsx
  apps/frontend/src/shared/hooks/useOverlay/useOverlay.test.tsx
  apps/frontend/src/shared/hooks/useOverlay/useOverlay.ts
Labels: ✨ Feature, 💻 Fe

#59 #54: 요청한 사용자의 gist 목록 조회
  apps/backend/src/gist/dto/response.allGists.dto.ts
  apps/backend/src/gist/dto/response.gist.dto.ts
  apps/backend/src/gist/gist.controller.ts
  apps/backend/src/gist/gist.service.ts
Labels: 💻 Be

#60 #53 oauth api
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/main.ts
  apps/backend/src/user/dto/user.create.dto.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.entity.ts
  apps/backend/src/user/user.service.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Be

#65 Feature #64: msw 세팅하기
  apps/frontend/package.json
  apps/frontend/public/mockServiceWorker.js
  apps/frontend/src/app/main.tsx
  apps/frontend/src/app/mock/browser.ts
  apps/frontend/src/app/mock/gistResolvers.ts
  apps/frontend/src/app/mock/handlers.ts
  apps/frontend/src/app/mock/lotusResolvers.ts
  apps/frontend/src/app/mock/userResolvers.ts
  pnpm-lock.yaml
Labels: 💻 Fe, ⚙️ Setting

#72 Feature #71 - LotusList 페이지 구현
  apps/frontend/src/app/mock/MockRepository/MockRepository.test.ts
  apps/frontend/src/app/mock/MockRepository/MockRepository.ts
  apps/frontend/src/app/mock/MockRepository/index.ts
  apps/frontend/src/app/mock/handlers.ts
  apps/frontend/src/app/mock/historyResolvers.ts
  apps/frontend/src/app/mock/lotusResolvers.ts
  apps/frontend/src/app/query/QueryProvider.tsx
  apps/frontend/src/app/router/RouteProvider.tsx
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/Lotus/api.ts
  apps/frontend/src/feature/Lotus/index.tsx
  apps/frontend/src/feature/Lotus/query.ts
  apps/frontend/src/feature/Lotus/type.ts
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/index.tsx
  apps/frontend/src/widget/LotusList/LotusCardList.tsx
  apps/frontend/src/widget/LotusList/LotusSearchBar.tsx
  apps/frontend/src/widget/LotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/LotusList/index.tsx
Labels: ✨ Feature, 💻 Fe

#68 history api 구현
  apps/backend/package.json
  apps/backend/src/ history/history.controller.ts
  apps/backend/src/ history/history.service.ts
  apps/backend/src/app.module.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/comment/comment.entity.ts
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/constants/constants.ts
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.module.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/gist/gist.controller.ts
  apps/backend/src/gist/gist.module.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/history/dto/history.execRequest.dto.ts
  apps/backend/src/history/dto/history.getReponse.dto.ts
  apps/backend/src/history/dto/history.pulbic.dto.ts
  apps/backend/src/history/dto/history.responseList.dto.ts
  apps/backend/src/history/history.controller.ts
  apps/backend/src/history/history.entity.ts
  apps/backend/src/history/history.module.ts
  apps/backend/src/history/history.repository.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/lotus/lotus.entity.ts
  apps/backend/src/tag/tag.entity.ts
  apps/backend/src/tag/tag.module.ts
  apps/backend/src/user/dto/user.create.dto.ts
  apps/backend/src/user/user.entity.ts
  pnpm-lock.yaml
Labels: 💻 Be

#70 swagger 추가
  apps/backend/package.json
  apps/backend/src/main.ts
Labels: 💻 Be

#74 Feature #73 - LotusDetail 페이지 구현
  apps/frontend/src/app/mock/historyResolvers.ts
  apps/frontend/src/app/mock/lotusResolvers.ts
  apps/frontend/src/feature/History/api.ts
  apps/frontend/src/feature/History/components/History.tsx
  apps/frontend/src/feature/History/index.tsx
  apps/frontend/src/feature/History/query.ts
  apps/frontend/src/feature/Lotus/Lotus.tsx
  apps/frontend/src/feature/Lotus/api.ts
  apps/frontend/src/feature/Lotus/query.ts
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/widget/History/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/History/index.tsx
  apps/frontend/src/widget/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/SuspenseLotusFiles.tsx
Labels: ✨ Feature, 💻 Fe

#76 tag api
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/history/dto/history.execRequest.dto.ts
  apps/backend/src/main.ts
  apps/backend/src/tag/dto/tag.createRequest.dto.ts
  apps/backend/src/tag/dto/tag.searchResponse.dto.ts
  apps/backend/src/tag/tag.controller.ts
  apps/backend/src/tag/tag.repository.ts
  apps/backend/src/tag/tag.service.ts
Labels: 💻 Be

#82 Feature #80 LotusDetailPage Mutation
  apps/frontend/src/app/main.tsx
  apps/frontend/src/app/mock/historyResolvers.ts
  apps/frontend/src/feature/History/api.ts
  apps/frontend/src/feature/History/components/History.tsx
  apps/frontend/src/feature/History/query.ts
  apps/frontend/src/feature/Lotus/api.ts
  apps/frontend/src/feature/Lotus/query.ts
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/index.tsx
  apps/frontend/src/shared/components/Overlay/ModalBox.tsx
  apps/frontend/src/shared/components/Overlay/index.tsx
  apps/frontend/src/shared/components/TagInput.tsx
  apps/frontend/src/shared/hooks/useDebounce/index.ts
  apps/frontend/src/shared/hooks/useDebounce/useDebounce.ts
  apps/frontend/src/widget/History/HistoryTrigger.tsx
  apps/frontend/src/widget/History/SuspenseLotusHistoryDetail.tsx
  apps/frontend/src/widget/History/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/HistoryList.tsx
  apps/frontend/src/widget/LotusCodeInput/CodeRunButton.tsx
  apps/frontend/src/widget/LotusCodeInput/LotusCodeDynamicInput.tsx
  apps/frontend/src/widget/LotusCodeInput/LotusCodeInputSection.tsx
  apps/frontend/src/widget/LotusCodeInput/LotusRunCodeForm.tsx
  apps/frontend/src/widget/LotusCodeInput/LotusRunFileSelect.tsx
  apps/frontend/src/widget/LotusCodeInput/index.tsx
  apps/frontend/src/widget/LotusDeleteButton.tsx
  apps/frontend/src/widget/LotusUpdateButton.tsx
  apps/frontend/src/widget/LotusUpdateForm.tsx
  apps/frontend/src/widget/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/SuspenseLotusPublicToggle.tsx
  packages/design/package.json
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/accordion.tsx
  packages/design/src/components/ui/select.tsx
  packages/design/src/components/ui/switch.tsx
  packages/design/tailwind.config.js
  packages/react-markdown/src/github.css
Labels: ✨ Feature, 💻 Fe

#81 history api 응답 dto 수정
  .github/workflows/cd.yml
  apps/backend/package.json
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/history/dto/history.execRequest.dto.ts
  apps/backend/src/history/dto/history.execResponse.dto.ts
  apps/backend/src/history/dto/history.getReponse.dto.ts
  apps/backend/src/history/dto/history.pulbic.dto.ts
  apps/backend/src/history/dto/history.responseList.dto.ts
  apps/backend/src/history/history.controller.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/main.ts
Labels: 💻 Be

#78 Feature #67 lotus crud
  apps/backend/src/app.module.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/gist/gist.controller.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/lotus/dto/lotus.detail.dto.ts
  apps/backend/src/lotus/dto/lotus.dto.ts
  apps/backend/src/lotus/dto/lotus.public.dto.ts
  apps/backend/src/lotus/dto/lotus.response.dto.ts
  apps/backend/src/lotus/dto/message.dto.ts
  apps/backend/src/lotus/dto/page.dto.ts
  apps/backend/src/lotus/dto/simple.file.response.dto.ts
  apps/backend/src/lotus/dto/simple.tag.response.dto.ts
  apps/backend/src/lotus/dto/simple.user.response.dto.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.entity.ts
  apps/backend/src/lotus/lotus.module.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.module.ts
Labels: ✨ Feature, 💻 Be

#85 Feature #83: lotus create
  apps/frontend/src/app/mock/gistResolvers.ts
  apps/frontend/src/feature/Lotus/api.ts
  apps/frontend/src/feature/Lotus/query.ts
  apps/frontend/src/feature/User/api.ts
  apps/frontend/src/feature/User/query.ts
  apps/frontend/src/page/(main)/lotus/create/index.lazy.tsx
  apps/frontend/src/shared/components/TagInput.tsx
  apps/frontend/src/widget/LotusCreate/LotusCreateForm.tsx
  apps/frontend/src/widget/LotusCreate/SuspenseGistFiles.tsx
  apps/frontend/src/widget/LotusCreate/SuspenseUserGistSelect.tsx
  apps/frontend/src/widget/LotusUpdateButton.tsx
Labels: ✨ Feature, 💻 Fe

#86 Feature #84 auth
  apps/frontend/eslint.config.js
  apps/frontend/src/app/mock/userResolvers.ts
  apps/frontend/src/feature/User/api.ts
  apps/frontend/src/feature/User/query.ts
  apps/frontend/src/shared/hooks/useLocalStorage/index.ts
  apps/frontend/src/shared/utils/api.ts
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/Navigation/CreateLotusButton.tsx
  apps/frontend/src/widget/Navigation/LoginButton.tsx
  apps/frontend/src/widget/Navigation/LogoutButton.tsx
  apps/frontend/src/widget/Navigation/index.tsx
Labels: ✨ Feature, 💻 Fe

#88 Feature #87: axios, Authenticated Routes, cursor 적용하기
  apps/frontend/src/app/query/QueryProvider.tsx
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/History/api.ts
  apps/frontend/src/feature/Lotus/api.ts
  apps/frontend/src/feature/User/api.ts
  apps/frontend/src/feature/User/query.ts
  apps/frontend/src/feature/User/utils/isAuthUser.ts
  apps/frontend/src/page/(main)/lotus/create/index.tsx
  apps/frontend/src/page/(main)/user/index.tsx
  apps/frontend/src/widget/LotusUpdateForm.tsx
  packages/design/src/components/ui/pagination.tsx
Labels: ✨ Feature, 💻 Fe, ♻️ Refactor

#92 Feature #91 toast & refactor useOverlay
  apps/frontend/src/shared/hooks/useOverlay/OverlayController.tsx
  apps/frontend/src/shared/hooks/useOverlay/useOverlay.test.tsx
  apps/frontend/src/shared/hooks/useOverlay/useOverlay.tsx
  apps/frontend/src/shared/hooks/useTimer/index.ts
  apps/frontend/src/shared/hooks/useToast/Toast.tsx
  apps/frontend/src/shared/hooks/useToast/index.tsx
  apps/frontend/src/shared/hooks/useToast/useToast.tsx
  apps/frontend/src/widget/LotusCodeInput/CodeRunButton.tsx
  apps/frontend/src/widget/LotusDeleteButton.tsx
  apps/frontend/src/widget/LotusUpdateButton.tsx
Labels: ✨ Feature, 💻 Fe, ♻️ Refactor

#95 Feature #94 fe cicd
  .github/workflows/fe-cd.yml
  apps/frontend/src/shared/utils/api.ts
  apps/frontend/tsconfig.app.json
  apps/frontend/tsconfig.node.json
  packages/design/package.json
  packages/react-markdown/index.html
  packages/react-markdown/package.json
  packages/react-markdown/vite.config.ts
  packages/react-markdown/vite.config.ts.timestamp-1731397235209-ff03ed3f3f3a4.mjs
  packages/react-markdown/vite.config.ts.timestamp-1731397318219-e73731b71ce51.mjs
Labels: 🌏 Deploy, 💻 Fe

#99 Feature #97: tanstack router devtools dev 모드 일때만 사용하기
  apps/frontend/src/app/router/RouteProvider.tsx
Labels: 💻 Fe, ⚙️ Setting

#101 Refactor(#94): fe-ci 라벨 분기 설정
  .github/workflows/fe-ci.yml
Labels: 🐞 BugFix, 💻 Fe

#100 api 테스트용 docker-compose
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  Dockerfile
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/history/history.controller.ts
  apps/backend/src/main.ts
  apps/backend/src/user/user.controller.ts
  docker-compose.yml
Labels: 🌏 Deploy

#93 Feature #69 lotus swagger and addtional feat
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/gist/dto/comment.dto.ts
  apps/backend/src/gist/dto/gist.commit.dto.ts
  apps/backend/src/gist/dto/gistApiFile.dto.ts
  apps/backend/src/gist/dto/gistApiFileList.dto.ts
  apps/backend/src/gist/dto/response.allGists.dto.ts
  apps/backend/src/gist/dto/response.gist.dto.ts
  apps/backend/src/gist/dto/user.dto.ts
  apps/backend/src/gist/gist.controller.ts
  apps/backend/src/history/history.controller.ts
  apps/backend/src/lotus/dto/lotus.createRequest.dto.ts
  apps/backend/src/lotus/dto/lotus.detail.dto.ts
  apps/backend/src/lotus/dto/lotus.dto.ts
  apps/backend/src/lotus/dto/lotus.public.dto.ts
  apps/backend/src/lotus/dto/lotus.response.dto.ts
  apps/backend/src/lotus/dto/lotus.updateRequest.dto.ts
  apps/backend/src/lotus/dto/message.dto.ts
  apps/backend/src/lotus/dto/page.dto.ts
  apps/backend/src/lotus/dto/simple.file.response.dto.ts
  apps/backend/src/lotus/dto/simple.tag.response.dto.ts
  apps/backend/src/lotus/dto/simple.user.response.dto.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.entity.ts
  apps/backend/src/lotus/lotus.module.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/tag/dto/tag.searchResponse.dto.ts
  apps/backend/src/tag/tag.controller.ts
  apps/backend/src/tag/tag.entity.ts
  apps/backend/src/tag/tag.service.ts
  apps/backend/src/user/dto/token.dto.ts
  apps/backend/src/user/dto/user.create.dto.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.service.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 Be

#103 Feature #102: gist controller 삭제 및 user 기능 재분배
  apps/backend/src/gist/dto/response.allGists.dto.ts
  apps/backend/src/gist/dto/response.gist.dto.ts
  apps/backend/src/gist/gist.controller.spec.ts
  apps/backend/src/gist/gist.controller.ts
  apps/backend/src/gist/gist.module.ts
  apps/backend/src/gist/gist.service.spec.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/user/dto/file.dto.ts
  apps/backend/src/user/dto/file.response.dto.ts
  apps/backend/src/user/dto/user.patch.dto.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.module.ts
  apps/backend/src/user/user.service.ts
  pnpm-lock.yaml
Labels: 💻 Be, ♻️ Refactor

#106 Feature #104: login 성공 실패 시 redirect 구현하기
  apps/frontend/src/app/mock/handlers.ts
  apps/frontend/src/app/mock/userResolvers.ts
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/page/index.lazy.tsx
  apps/frontend/src/page/login/fail/index.tsx
  apps/frontend/src/page/login/success/index.tsx
  apps/frontend/src/widget/LoginButton.tsx
Labels: 💻 Fe, ♻️ Refactor

#107 Feature #104: login/error 토스트 문제 해결하기
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/page/login/error/index.tsx
  apps/frontend/src/page/login/fail/index.tsx
  apps/frontend/vite.config.ts
Labels: 🐞 BugFix, 💻 Fe

#110 Feature #105 git oauth redirect url
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/history/dto/history.pulbic.dto.ts
  apps/backend/src/history/history.controller.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/lotus/dto/lotus.updateRequest.dto.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.entity.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/user/user.controller.ts
Labels: 🐞 BugFix, 💻 Be

#116 Feature #115 codeviewer
  apps/frontend/src/feature/codeView/component/CodeSideBar.tsx
  apps/frontend/src/feature/codeView/component/CodeViewProvider.tsx
  apps/frontend/src/feature/codeView/component/CodeViewer.tsx
  apps/frontend/src/feature/lotus/component.tsx
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/lotusCreate/SuspenseGistFiles.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusFiles.tsx
Labels: 🐞 BugFix, 💻 Fe

#118 history excetion 및 docker execute tty 수정
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/constants/constants.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/main.ts
  apps/backend/src/user/user.service.ts
Labels: 💻 Be

#121 Feature #117 LotusDetail Loading fallback
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/lotusDelete/index.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusFiles.tsx
  apps/frontend/src/widget/lotusUpdate/LotusUpdateButton.tsx
  apps/frontend/src/widget/lotusUpdate/SuspenseLotusPublicToggle.tsx
  packages/design/src/components/index.tsx
  packages/design/src/components/ui/skeleton.tsx
Labels: ✨ Feature, 💻 Fe

#122 Feature #120: pagination 적용 및 로그인 처리 수정하기
  apps/frontend/src/feature/lotus/api.ts
  apps/frontend/src/feature/user/api.ts
  apps/frontend/src/feature/user/query.ts
  apps/frontend/src/feature/user/util.ts
  apps/frontend/src/page/(main)/lotus/create/index.tsx
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/page/(main)/user/index.lazy.tsx
  apps/frontend/src/page/(main)/user/index.tsx
  apps/frontend/src/page/login/success/index.tsx
  apps/frontend/src/shared/pagination/Pagination.tsx
  apps/frontend/src/shared/pagination/index.ts
  apps/frontend/src/shared/pagination/type.ts
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusPagination.tsx
  apps/frontend/src/widget/lotusList/SuspenseUserLotusPagination.tsx
  apps/frontend/src/widget/navigation/LogoutButton.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
  apps/frontend/src/widget/user/SuspenseUserLotusList.tsx
Labels: 🐞 BugFix, ✨ Feature, 💻 Fe

#119 Fix #113: 에러 처리 추가 및 user 정보 수정 optional하게 변경
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/gist/dto/gistApiFile.dto.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/user/dto/user.patch.dto.ts
  apps/backend/src/user/user.service.ts
Labels: 🐞 BugFix, 💻 Be

#126 Fix #125: 새로고침 시에 로그인 상태 유지 못하는 에러 수정하기
  apps/frontend/src/feature/user/util.ts
  apps/frontend/src/page/(main)/lotus/create/index.tsx
  apps/frontend/src/page/(main)/user/index.tsx
Labels: 🐞 BugFix, 💻 Fe

#127 Refactor #117: lotus 목록 페이지의 fallback ui 구현하기
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/shared/common/index.ts
  apps/frontend/src/shared/common/util.ts
  apps/frontend/src/shared/pagination/Pagination.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusPagination.tsx
Labels: 💻 Fe, ♻️ Refactor

#128 Feature #117 : 사용자 정보 페이지의 fallback ui 구현하기
  apps/frontend/src/page/(main)/user/index.lazy.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusPagination.tsx
  apps/frontend/src/widget/lotusList/SuspenseUserLotusPagination.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
  apps/frontend/src/widget/user/SuspenseUserLotusList.tsx
Labels: ✨ Feature, 💻 Fe

#132 Fix #131 : useToast hook 버그
  apps/frontend/src/page/login/success/index.tsx
  apps/frontend/src/shared/common/hook/useTimer.ts
  apps/frontend/src/shared/toast/Toast.tsx
  apps/frontend/src/shared/toast/useToast.tsx
Labels: 🐞 BugFix, 💻 Fe

#130 Fix #129 비로그인 사용자 버그 수정 및 tag 버그 수정
  apps/backend/src/history/history.controller.ts
  apps/backend/src/lotus/lotus.controller.ts
  apps/backend/src/lotus/lotus.service.ts
Labels: 🐞 BugFix, 💻 Be

#135 Feature #133: useDebounce, useTagInput 테스트 코드
  apps/frontend/src/shared/common/component/index.ts
  apps/frontend/src/shared/common/hook/useDebounce.test.ts
  apps/frontend/src/shared/tagInput/TagInput.tsx
  apps/frontend/src/shared/tagInput/index.ts
  apps/frontend/src/shared/tagInput/useTagInput.test.tsx
  apps/frontend/src/shared/tagInput/useTagInput.ts
  apps/frontend/src/widget/lotusCreate/LotusCreateForm.tsx
  apps/frontend/src/widget/lotusUpdate/LotusUpdateForm.tsx
Labels: ✅ Test, 💻 Fe

#139 Refactor: QueryKey Factory를 통한 QueryKey 구조화
  apps/frontend/eslint.config.js
  apps/frontend/src/feature/history/query.ts
  apps/frontend/src/feature/lotus/api.ts
  apps/frontend/src/feature/lotus/index.ts
  apps/frontend/src/feature/lotus/query.ts
  apps/frontend/src/feature/user/query.ts
  apps/frontend/src/feature/user/util.ts
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/page/(main)/user/index.lazy.tsx
  apps/frontend/src/page/login/success/index.tsx
  apps/frontend/src/shared/createQueryOptions/createQueryOptions.test.ts
  apps/frontend/src/shared/createQueryOptions/createQueryOptions.ts
  apps/frontend/src/shared/createQueryOptions/index.ts
  apps/frontend/src/shared/createQueryOptions/type.ts
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryDetail.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/lotusCodeRun/LotusRunFileSelect.tsx
  apps/frontend/src/widget/lotusCreate/SuspenseGistFiles.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusFiles.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusPagination.tsx
  apps/frontend/src/widget/lotusList/SuspenseUserLotusPagination.tsx
  apps/frontend/src/widget/lotusList/type.ts
  apps/frontend/src/widget/lotusUpdate/LotusUpdateForm.tsx
  apps/frontend/src/widget/lotusUpdate/SuspenseLotusPublicToggle.tsx
  apps/frontend/src/widget/navigation/LogoutButton.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
  apps/frontend/src/widget/user/SuspenseUserLotusList.tsx
  apps/frontend/src/widget/user/index.ts
Labels: 💻 Fe, ♻️ Refactor

#140 history가 PENDING에서 업데이트 되지않던 문제 해결
  .github/workflows/be-cd.yml
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/filter/ typeorm.exception.filter.ts
  apps/backend/src/filter/http.exception.filter.ts
  apps/backend/src/gist/.gist.controller.spec.ts.icloud
  apps/backend/src/gist/.gist.service.spec.ts.icloud
  apps/backend/src/history/history.controller.ts
  apps/backend/src/history/history.entity.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/main.ts
  apps/backend/src/user/user.service.ts
Labels: 💻 Be

#144 Fix(#138): invalidateQueries에서 queryOptions 사용
  apps/frontend/src/widget/lotusCodeRun/CodeRunButton.tsx
  apps/frontend/src/widget/lotusUpdate/LotusUpdateButton.tsx
Labels: 💻 Fe, ♻️ Refactor

#148 Fix #147: user 정보 업데이트 에러 수정
  apps/backend/src/user/user.service.ts
Labels: 🐞 BugFix, 💻 Be

#143 도커 package설치 및 timeout 제한 추가
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/gist/.gist.controller.spec.ts.icloud
  apps/backend/src/gist/.gist.service.spec.ts.icloud
Labels: 💻 Be

#146 Feature #145 mutation 결과 toast로 띄우기
  apps/frontend/src/feature/user/component.tsx
  apps/frontend/src/widget/lotusCodeRun/CodeRunButton.tsx
  apps/frontend/src/widget/lotusCreate/LotusCreateForm.tsx
  apps/frontend/src/widget/lotusDelete/index.tsx
  apps/frontend/src/widget/lotusUpdate/LotusUpdateButton.tsx
  apps/frontend/src/widget/lotusUpdate/LotusUpdateForm.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
Labels: ✨ Feature, 💻 Fe

#157 Fix #152#153#156 lotus sort etc
  apps/backend/src/docker/docker.service.ts
  apps/backend/src/filter/typeorm.exception.filter.ts
  apps/backend/src/lotus/dto/lotus.detail.dto.ts
  apps/backend/src/lotus/dto/lotus.response.dto.ts
  apps/backend/src/lotus/dto/simple.user.response.dto.ts
  apps/backend/src/lotus/lotus.service.ts
  apps/backend/src/main.ts
  apps/backend/src/user/dto/user.create.dto.ts
  apps/backend/src/user/user.entity.ts
Labels: 🐞 BugFix, ✨ Feature, 💻 Be

#158 Feature #155 : History Pagination, History Pending Error
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/history/api.ts
  apps/frontend/src/feature/lotus/api.ts
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/$lotusId/index.tsx
  apps/frontend/src/shared/pagination/Pagination.tsx
  apps/frontend/src/shared/pagination/usePagination.tsx
  apps/frontend/src/widget/SuspensePagination.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryDetail.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/lotusCodeRun/CodeRunButton.tsx
  apps/frontend/src/widget/lotusCodeRun/LotusRunCodeForm.tsx
  packages/react-markdown/src/github.css
Labels: 💻 Fe, ♻️ Refactor

#154 Feature #145 LotusMutationErrorToast
  apps/frontend/src/feature/lotus/api.ts
  apps/frontend/src/feature/lotus/index.ts
  apps/frontend/src/feature/lotus/util.ts
  apps/frontend/src/shared/toast/Toast.tsx
  apps/frontend/src/widget/lotusCreate/LotusCreateForm.tsx
  apps/frontend/src/widget/lotusDelete/index.tsx
  apps/frontend/src/widget/lotusUpdate/LotusUpdateButton.tsx
Labels: ✨ Feature, 💻 Fe

#160 Feature #159 SuspensePagination 변경, 검색 api 추가, 프론트엔드 환경 수정
  .gitignore
  apps/frontend/index.html
  apps/frontend/public/android-chrome-192x192.png
  apps/frontend/public/android-chrome-512x512.png
  apps/frontend/public/apple-touch-icon.png
  apps/frontend/public/favicon-16x16.png
  apps/frontend/public/favicon-32x32.png
  apps/frontend/public/favicon.ico
  apps/frontend/public/site.webmanifest
  apps/frontend/src/feature/lotus/api.ts
  apps/frontend/src/feature/lotus/hook.ts
  apps/frontend/src/feature/lotus/index.ts
  apps/frontend/src/feature/user/api.ts
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/index.tsx
  apps/frontend/src/page/(main)/user/index.lazy.tsx
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusFiles.tsx
  apps/frontend/src/widget/lotusList/LotusSearchBar.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusPagination.tsx
  docker-compose.yml
Labels: 💻 Fe, ♻️ Refactor

#162 Feature #161: search를 tag가 아닌 title로 하도록 수정
  apps/backend/src/lotus/lotus.service.ts
Labels: ✨ Feature, 💻 Be

#163 Feature #117: error fallback 적용하기
  apps/frontend/public/json/errorAnimation.json
  apps/frontend/src/feature/lotus/util.ts
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/create/index.lazy.tsx
  apps/frontend/src/page/(main)/lotus/index.lazy.tsx
  apps/frontend/src/page/(main)/user/index.lazy.tsx
  apps/frontend/src/shared/common/component/GlobalError.tsx
  apps/frontend/src/shared/common/component/index.ts
  apps/frontend/src/widget/history/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/lotusCreate/LotusCreateForm.tsx
  apps/frontend/src/widget/lotusCreate/SuspenseGistFiles.tsx
  apps/frontend/src/widget/lotusCreate/SuspenseUserGistSelect.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
Labels: ✨ Feature, 💻 Fe

#165 Feature #164 feature model 계층으로 리팩터링
  apps/frontend/src/app/main.tsx
  apps/frontend/src/app/mock/lotusResolvers.ts
  apps/frontend/src/feature/codeView/component/CodeViewProvider.tsx
  apps/frontend/src/feature/codeView/component/CodeViewer.tsx
  apps/frontend/src/feature/codeView/constant.ts
  apps/frontend/src/feature/codeView/hook.ts
  apps/frontend/src/feature/codeView/index.ts
  apps/frontend/src/feature/codeView/model.ts
  apps/frontend/src/feature/codeView/type.ts
  apps/frontend/src/feature/history/api.ts
  apps/frontend/src/feature/history/component.tsx
  apps/frontend/src/feature/history/index.ts
  apps/frontend/src/feature/history/model.ts
  apps/frontend/src/feature/history/type.ts
  apps/frontend/src/feature/lotus/api.ts
  apps/frontend/src/feature/lotus/component.tsx
  apps/frontend/src/feature/lotus/index.ts
  apps/frontend/src/feature/lotus/model.ts
  apps/frontend/src/feature/lotus/type.ts
  apps/frontend/src/feature/pagination/Pagination.tsx
  apps/frontend/src/feature/pagination/index.ts
  apps/frontend/src/feature/pagination/type.ts
  apps/frontend/src/feature/pagination/usePagination.tsx
  apps/frontend/src/feature/user/api.ts
  apps/frontend/src/feature/user/component/User.tsx
  apps/frontend/src/feature/user/component/UserInfoInputForm.tsx
  apps/frontend/src/feature/user/component/index.ts
  apps/frontend/src/feature/user/index.ts
  apps/frontend/src/feature/user/model.ts
  apps/frontend/src/feature/user/type.ts
  apps/frontend/src/feature/user/util.ts
  apps/frontend/src/page/(main)/route.lazy.tsx
  apps/frontend/src/shared/pagination/type.ts
  apps/frontend/src/widget/SuspensePagination.tsx
  apps/frontend/src/widget/history/HistoryTrigger.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/lotusCreate/LotusCreateForm.tsx
  apps/frontend/src/widget/lotusCreate/SuspenseGistFiles.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusFiles.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/lotusList/type.ts
  apps/frontend/src/widget/lotusUpdate/LotusUpdateForm.tsx
  apps/frontend/src/widget/lotusUpdate/SuspenseLotusPublicToggle.tsx
Labels: 💻 Fe, ♻️ Refactor

#167 Fix(#166): lotus Edit버튼에서 user token 401 error 페이지 깨짐 해결
  apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusEdit.tsx
  apps/frontend/src/widget/lotusDetail/index.ts
Labels: 🐞 BugFix, 💻 Fe

#169 Refactor #97: github 로그인 클라이언트에서 인가코드 받는 것으로 수정하기
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/user/user.controller.ts
  apps/backend/src/user/user.service.ts
  apps/frontend/src/app/router/routeTree.gen.ts
  apps/frontend/src/feature/user/api.ts
  apps/frontend/src/feature/user/query.ts
  apps/frontend/src/page/login/error/index.tsx
  apps/frontend/src/page/login/index.tsx
  apps/frontend/src/widget/navigation/LoginButton.tsx
Labels: 💻 Fe, ♻️ Refactor

#170 Feature #168 프론트 퍼블리싱
  apps/frontend/index.html
  apps/frontend/public/json/emptyHistoryAnimation.json
  apps/frontend/src/app/style/github.css
  apps/frontend/src/page/index.lazy.tsx
  apps/frontend/src/widget/Header.tsx
  apps/frontend/src/widget/history/SuspenseLotusHistoryList.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusFiles.tsx
  apps/frontend/src/widget/lotusList/LotusSearchBar.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
  apps/frontend/src/widget/onboarding/OnBoardingCarousel.tsx
  apps/frontend/src/widget/onboarding/constant.tsx
  apps/frontend/src/widget/onboarding/index.ts
  packages/design/package.json
  packages/design/src/components/ui/pagination.tsx
  packages/design/src/components/ui/skeleton.tsx
  packages/design/src/index.ts
Labels: 💻 Fe

#175 컨테이너 스케줄링
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/config/queue.config.ts
  apps/backend/src/config/typeorm.config.ts
  apps/backend/src/constants/constants.ts
  apps/backend/src/docker/docker.consumer.ts
  apps/backend/src/docker/docker.controller.ts
  apps/backend/src/docker/docker.module.ts
  apps/backend/src/docker/docker.pool.ts
  apps/backend/src/docker/docker.producer.ts
  apps/backend/src/gist/gist.service.ts
  apps/backend/src/history/history.service.ts
  apps/backend/src/user/user.service.ts
  apps/frontend/src/feature/codeView/index.tsx
  apps/frontend/src/feature/comment/index.tsx
  apps/frontend/src/shared/.gitkeep
  apps/frontend/src/widget/.gitkeep
  apps/frontend/src/widget/lotusList/index.tsx
  pnpm-lock.yaml
Labels: 💻 Be

#174 Refactor #172: 사용자 정보 페이지에서 gist address 조회하기
  apps/frontend/src/page/index.lazy.tsx
  apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
Labels: 🐞 BugFix, 💻 Fe, ♻️ Refactor

#177 Feature(#176): lotus list, lotus detail에 gist 바로가기 추가
  apps/frontend/src/feature/lotus/component.tsx
  apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
  apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx
Labels: ✨ Feature, 💻 Fe

#178 cd 브랜치 변경
  .github/workflows/be-cd.yml
  .github/workflows/fe-cd.yml
Labels: 🌏 Deploy

#179 deploy
  .github/workflows/be-cd.yml
  .github/workflows/fe-cd.yml
Labels: 🌏 Deploy

#181 도커를 삭제하던 이전 코드 삭제
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  .github/workflows/fe-cd.yml
  .github/workflows/fe-ci.yml
  apps/backend/src/docker/docker.consumer.ts
Labels: 🐞 BugFix, 💻 Be

#185 무한루프 오류 해결
  apps/backend/src/docker/docker.consumer.ts
  apps/backend/src/history/history.service.ts
Labels: 💻 Be
